teleport-delay: 5
#-1 = Infinity Effect
nightvision-duration: 999999 # Ù…Ø¯Øª Ø²Ù…Ø§Ù† ÙØ¹Ø§Ù„ Ø¨ÙˆØ¯Ù† Ø§ÙÚ©Øª Ù†Ø§ÛŒØª ÙˆÛŒÚ˜Ù† (Ø¯Ø± ØªÛŒÚ©â€ŒÙ‡Ø§)
#Level Effect
nightvision-amplifier: 0
messages:
  creative: "&x&E&3&3&4&1&4â„¹ &eÊá´á´œÊ€ É¢á´€á´á´‡ á´á´á´…á´‡ Êœá´€êœ± Ê™á´‡á´‡É´ á´„Êœá´€É´É¢á´‡á´… á´›á´ &cá´„Ê€á´‡á´€á´›Éªá´ á´‡."
  adventure: "&x&E&3&3&4&1&4â„¹ &eÊá´á´œÊ€ É¢á´€á´á´‡ á´á´á´…á´‡ Êœá´€êœ± Ê™á´‡á´‡É´ á´„Êœá´€É´É¢á´‡á´… á´›á´ &cá´€á´…á´ á´‡É´á´›á´œÊ€á´‡."
  survival: "&x&E&3&3&4&1&4â„¹ &eÊá´á´œÊ€ É¢á´€á´á´‡ á´á´á´…á´‡ Êœá´€êœ± Ê™á´‡á´‡É´ á´„Êœá´€É´É¢á´‡á´… á´›á´ &cêœ±á´œÊ€á´ Éªá´ á´€ÊŸ."
  spectator: "&x&E&3&3&4&1&4â„¹ &eÊá´á´œÊ€ É¢á´€á´á´‡ á´á´á´…á´‡ Êœá´€êœ± Ê™á´‡á´‡É´ á´„Êœá´€É´É¢á´‡á´… á´›á´ &cêœ±á´˜á´‡á´„á´›á´€á´›á´Ê€."
  not-a-player: "&x&E&3&3&4&1&4ğŸš« &fá´›ÊœÉªêœ± á´„á´á´á´á´€É´á´… á´„á´€É´ á´É´ÊŸÊ Ê™á´‡ á´œêœ±á´‡á´… Ê™Ê á´˜ÊŸá´€Êá´‡Ê€êœ±."
  no-argument: "&x&E&3&3&4&1&4â“ &fPlease specify an argument: &6hand &for &6all&f."
  invalid-argument: "&x&E&3&3&4&1&4ğŸš« &fá´˜ÊŸá´‡á´€êœ±á´‡ êœ±á´˜á´‡á´„Éªêœ°Ê á´€É´ á´€Ê€É¢á´œá´á´‡É´á´›: &6Êœá´€É´á´… &êœ°á´Ê€ &6á´€ÊŸÊŸ&f."
  repaired-hand: "&x&E&3&3&4&1&4ğŸ”§ &fÊá´á´œÊ€ Éªá´›á´‡á´ ÉªÉ´ Êœá´€É´á´… &e({item})&f Êœá´€êœ± Ê™á´‡á´‡É´ Ê€á´‡á´˜á´€ÉªÊ€á´‡á´…."
  repaired-all: "&x&E&3&3&4&1&4ğŸ”§ &fá´€ÊŸÊŸ Éªá´›á´‡á´êœ± ÉªÉ´ Êá´á´œÊ€ ÉªÉ´á´ á´‡É´á´›á´Ê€Ê Êœá´€á´ á´‡ Ê™á´‡á´‡É´ Ê€á´‡á´˜á´€ÉªÊ€á´‡á´…."
  spawn-set: "&x&E&3&3&4&1&4â„¹ &aêœ±á´˜á´€á´¡É´ ÊŸá´á´„á´€á´›Éªá´É´ êœ±á´‡á´›!"
  spawn-not-set: "&x&E&3&3&4&1&4â„¹ êœ±á´˜á´€á´¡É´ ÊŸá´á´„á´€á´›Éªá´É´ Êœá´€êœ± É´á´á´› Ê™á´‡á´‡É´ êœ±á´‡á´› Êá´‡á´›!"
  teleporting: "&x&E&3&3&4&1&4â„¹ &eá´›á´‡ÊŸá´‡á´˜á´Ê€á´›ÉªÉ´É¢ ÉªÉ´ %d êœ±á´‡á´„á´É´á´…êœ±..."
  teleport-cancelled: "&x&E&3&3&4&1&4â„¹ &cá´›á´‡ÊŸá´‡á´˜á´Ê€á´› á´›á´ êœ±á´˜á´€á´¡É´ á´„á´€É´á´„á´‡ÊŸÊŸá´‡á´… á´…á´œá´‡ á´›á´ á´á´á´ á´‡á´á´‡É´á´›."
  teleported: "&x&E&3&3&4&1&4â„¹ &aá´›á´‡ÊŸá´‡á´˜á´Ê€á´›á´‡á´… á´›á´ êœ±á´˜á´€á´¡É´!"
  no-permission: "&x&E&3&3&4&1&4â„¹ &cÊá´á´œ á´…á´ É´á´á´› Êœá´€á´ á´‡ á´˜á´‡Ê€á´Éªêœ±êœ±Éªá´É´ á´›á´ á´œêœ±á´‡ á´›ÊœÉªêœ± á´„á´á´á´á´€É´á´…."
  target: "&x&E&3&3&4&1&4â„¹ &aÊá´á´œ á´„Êœá´€É´É¢á´‡á´… &b%player%'êœ± &aÉ¢á´€á´á´‡ á´á´á´…á´‡ á´›á´ &b%mode%."
  player-not-found: "&cPlayer not found."
  flight-enabled: "&aFlight enabled for {player}."
  flight-disabled: "&cFlight disabled for {player}."
  usage: "&cUsage: /fly [playername] enable/disable"
  invalid_argument: "&cInvalid argument. Use 'enable' or 'disable'."
  nightvision-activated: "&3NightVision &aActivated"
  nightvision-disabled: "&3NightVision &cDisabled"